# Generated by Django 4.2.20 on 2026-10-05 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='菜谱名称')),
                ('category', models.CharField(max_length=100, verbose_name='分类')),
                ('ingredients', models.TextField(verbose_name='食材')),
                ('steps', models.TextField(verbose_name='制作步骤')),
                ('image', models.ImageField(blank=True, upload_to='recipe_img/')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
